module.exports = [
  {
    _id: 111111,
    title: 'new iPhone 7/7plus',
    image: 'https://pbs.twimg.com/profile_images/742733520141852673/SUE_e4jK.jpg',
    desc: 'new iphone 7 presented last week has bad quality',
    data: '<h2>new iphone 7 presented last week has bad quality</h2>'+
          '<img class="banner" src="https://www.unifone.com.au/media/cms_asset/iphone-7-banner.jpg"/>'+
          '<div>orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took</div>'
  },
  {
    _id: 222222,
    title: "Ex-Apprentice insiders blast Trump's 'sexist' remarks",
    image: "http://ichef-1.bbci.co.uk/news/660/cpsprodpb/13F24/production/_91500718_5eef05b4-b6a1-43f4-b63b-f5afc1fb19d7.jpg",
    desc: "Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.Republican presidential candidate Donald Trump has been accused by ex-contestants and staff on reality show The Apprentice of sexism, according to an Associated Press investigation.",
    data: '<h2>Trump lox</h2>'+
          "<div>More than 20 people interviewed described Mr Trump's behaviour toward women as crass and inappropriate.Mr Trump's campaign dismissed the allegations.Spokeswoman Hope Hicks said they were outlandish, unsubstantiated and totally false.Mr Trump has faced several allegations over the past week questioning his fitness to be president of the US.On Sunday, the New York Times published evidence which alleged that Mr Trump may not have paid federal income tax for 20 years.</div>"
  }
]